### ISSUE TITLE
Expand Inventory Class & Implement Active Inventory

### ISSUE THREAD

**Issue by HaydenStegman** [CSI-280/TheGameOfJim#20]
The inventory class is very basic allowing for the addition and deletion of items.
The active inventory (This being the items the player has equipped) needs to be implements.
This is an array of Items with 4 (Subject to change) slots [Weapon, Head Armor, Chest Armor, Leg Armor]

This needs to be implemented so that the player can move items between the Active Inventory and the Player Inventory. A player should only be able to put an item in a slot that the Item is of the correct type for that slot. So **Item class is a blocker for this**.

**Comment by phllpbll189** [comment]
i was wondering about something in your inventory system. So instead of doing check for a specific item in an inventory, why not print out everything in the inventory as organized as possible?

Then the player could look in the inventory and see if its in there himself. Also it might be easy to set up and later we can refine it.

**Comment by HaydenStegman** [comment]
@phllpbll189  The checkPlayerInventoryForItem is for other classes to call. Not the player. Say a door is locked and requires the player to have a key. The Room Class could call that function to check for the item.

**Comment by PointlessVenture** [comment]
I added a function while i was working on this ( #5 / #21 ) that would spit out the item. Functions in the game can now make the inventory print it's content, which is needed to put things in a container.
